### ISSUE TITLE
Gateway Intents

### ISSUE THREAD

**Issue by alanhuang122** [alanhuang122/IRCdiscord#10]
As Discord is moving to Gateway Intents and restricting access to Request Guild Members (requiring [bot] token whitelisting to set the `GUILD_MEMBERS` intent), creation of the user list on connection to a guild is currently no longer possible.

It may be possible to work around this (by perhaps iterating through the alphabet [this approach suffers from probably missing users (100 user limit per call to Request Guild Members)], or sending JOINs on `discordGuildSession.addMember` [will not get QUITs, or JOINs or NICKs before a message is sent]), but for now, there will not be a way to get the user list. It is possible that Discord will change this in future, though I'm not counting on it.

**Comment by alanhuang122** [comment]
Emulating the behavior of the official discord client might work: https://luna.gitlab.io/discord-unofficial-docs/lazy_guilds.html

**Comment by diamondburned** [comment]
Gateway Intents are a Bot API thing (as far as I know). The client does use the "lazy guilds" API, or as I like to call it, Subscribe Guild API.

That said, I just added that API into [ningen](https://github.com/diamondburned/ningen), which added a state and abstracted some event handlers. This should make it easier.

**Comment by diamondburned** [comment]
The only issue would be knowing when to fetch the rest of the members list, as you can only fetch part of it and have Discord send update events. Perhaps an arbitrarily large number (200 or so) would suffice.
